# version format
version: 1.9.9-{branch}-build{build}

os: Visual Studio 2019

clone_folder: c:\projects\mrpt

platform: x64
configuration: Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

build:
  project: c:\projects\mrpt\build\MRPT.sln

install:
  # Install OpenCV
  - choco upgrade chocolatey
  - choco install opencv -y
#  - tree c:\tools\opencv\build /F
  - set OPENCVDIR=C:\tools\opencv\build\
  - set PATH=%PATH%;%OPENCVDIR%\bin;%OPENCVDIR%\x64\vc15\bin
  # Install wxWidgets
  - cd c:\
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxMSW-3.1.3_vc14x_x64_Dev.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3-headers.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxMSW-3.1.3_vc14x_x64_ReleaseDLL.7z'
  - 7z x wxMSW-3.1.3_vc14x_x64_Dev.7z -oc:\wxWidgets -aoa
  - 7z x wxWidgets-3.1.3-headers.7z -oc:\wxWidgets -aoa
  - 7z x wxMSW-3.1.3_vc14x_x64_ReleaseDLL.7z -oc:\wxWidgets -aoa
  - set WXWIDGETSDIR=C:\wxWidgets
  - set WXWIDGETSLIBDIR=%WXWIDGETSDIR%\lib\vc14x_x64_dll\
#  - tree %WXWIDGETSDIR% /F
  - set PATH=%PATH%;%WXWIDGETSLIBDIR%
  # Qt:
  - set QTDIR=C:\Qt\5.14.1\msvc2017_64
#  - dir %QTDIR%\bin
  - set PATH=%PATH%;%QTDIR%\bin
  - PATH

before_build:
  - cd c:\projects\mrpt
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - set VERBOSE=1 # for MRPT cmake scripts to show more info
  - cmake -G "Visual Studio 16 2019" -DEIGEN_USE_EMBEDDED_VERSION=ON -DBUILD_ASSIMP=OFF -DOpenCV_DIR=%OPENCVDIR% -DwxWidgets_ROOT_DIR=%WXWIDGETSDIR% -DwxWidgets_LIB_DIR=%WXWIDGETSLIBDIR% ..

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

